apiVersion: v1
kind: Service
metadata:
  name: zulip-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: zulip
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
