apiVersion: v1
kind: Service
metadata:
  name: zulip-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # Optional, for AWS LoadBalancer type
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: zulip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
