apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      component: redis
  template:
    metadata:
      labels:
        app: chat
        component: redis
    spec:
      containers:
      - name: redis
        image: quay.io/sameersbn/redis:latest
        resources:
          limits:
            cpu: 1
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /var/lib/redis
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zulip-redis-data
