# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: zulip-postgres-data
#   namespace: default
#   labels:
#     app: chat
#     tier: data
# spec:
#   storageClassName: standard
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
