apiVersion: v1
kind: Service
metadata:
  name: zulip-postgres
  namespace: default
  labels:
    app: chat
spec:
  selector:
    app: chat
    component: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
