apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip-rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      component: rabbitmq
  template:
    metadata:
      labels:
        app: chat
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.7
        resources:
          limits:
            cpu: 1
            memory: 1Gi
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "zulip"
        - name: RABBITMQ_DEFAULT_PASS
          value: "${ZULIP_RABBITMQ_PASSWORD}"
        volumeMounts:
          - name: data
            mountPath: /var/lib/rabbitmq
        ports:
          - name: rabbitmq
            containerPort: 5672
            protocol: TCP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zulip-rabbitmq-data
