apiVersion: v1
kind: Service
metadata:
  name: zulip-rabbitmq
  namespace: default
  labels:
    app: chat
spec:
  selector:
    app: chat
    component: rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
    protocol: TCP
