apiVersion: v1
kind: Service
metadata:
  name: zulip-memcached
  namespace: default
  labels:
    app: chat
spec:
  selector:
    app: chat
    component: memcached
  ports:
  - name: memcached
    port: 11211
    targetPort: 11211
    protocol: TCP
