apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: zulip/zulip-postgresql
          env:
            - name: POSTGRES_DB
              value: zulip
            - name: POSTGRES_USER
              value: zulip
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: zulip-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: zulip-postgres-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
