apiVersion: v1
kind: Service
metadata:
  name: zulip-redis
  namespace: chat
  labels:
    app: chat
spec:
  selector:
    app: chat
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP